return {
  { texture = nil, ptr = nil, action = nil, name = 'carbuncle', commands = {
    { texture = nil, ptr = nil, action = nil, command = 'assault',          target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'retreat',          target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'release',          target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'poison nails',     target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'meteorite',        target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'holy mist',        target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'healing ruby',     target = '<stpc>',  ranks = 2 },
    { texture = nil, ptr = nil, action = nil, command = 'shining ruby',     target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'glittering ruby',  target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'soothing ruby',    target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'pacifying ruby',   target = '<me>',    ranks = 1 },
  } },
  { texture = nil, ptr = nil, action = nil, name = 'titan', commands = {
    { texture = nil, ptr = nil, action = nil, command = 'assault',          target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'retreat',          target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'release',          target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'stone',            target = '<stnpc>', ranks = 4 },
    { texture = nil, ptr = nil, action = nil, command = 'rock buster',      target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'megalith throw',   target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'mountain buster',  target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'geocrush',         target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'crag throw',       target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'earthen ward',     target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'earthen armor',    target = '<me>',    ranks = 1 },
  } },
  { texture = nil, ptr = nil, action = nil, name = 'leviathan', commands = {
    { texture = nil, ptr = nil, action = nil, command = 'assault',          target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'retreat',          target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'release',          target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'barracuda dive',   target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'water',            target = '<stnpc>', ranks = 4 },
    { texture = nil, ptr = nil, action = nil, command = 'tail whip',        target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'spinning dive',    target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'grand fall',       target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'slowga',           target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'spring water',     target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'tidal roar',       target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'soothing current', target = '<me>',    ranks = 1 },
  } },
  { texture = nil, ptr = nil, action = nil, name = 'garuda', commands = {
    { texture = nil, ptr = nil, action = nil, command = 'assault',          target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'retreat',          target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'release',          target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'claw',             target = '<stnpc>', ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'aero',             target = '<stnpc>', ranks = 4 },
    { texture = nil, ptr = nil, action = nil, command = 'predator claws',   target = '<stnpc>',  ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'wind blade',       target = '<stnpc>',  ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'aerial armor',     target = '<me>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'whispering wind',  target = '<stpc>',    ranks = 1 },
    { texture = nil, ptr = nil, action = nil, command = 'hastega',          target = '<me>',    ranks = 2 },
    { texture = nil, ptr = nil, action = nil, command = 'fleet wind',       target = '<me>',    ranks = 1 },
  } },
  { texture = nil, ptr = nil, action = nil, name = 'ifrit' },
  { texture = nil, ptr = nil, action = nil, name = 'shiva' },
  { texture = nil, ptr = nil, action = nil, name = 'ramuh' },
  { texture = nil, ptr = nil, action = nil, name = 'fenrir' },
  { texture = nil, ptr = nil, action = nil, name = 'diabolos' },
  { texture = nil, ptr = nil, action = nil, name = 'cait sith' },
  { texture = nil, ptr = nil, action = nil, name = 'atomos' },
  { texture = nil, ptr = nil, action = nil, name = 'siren' },
};
